### ISSUE TITLE
Prevent a user form logging in from 2 devices at once

### ISSUE THREAD

**Issue by Gil4390** [talgalm/Beautiful-Images-Project#17]
- add column 'loggedIn' in the Users table
- upon login/logout update the field
- create a logout function in the server that corresponds to the function tal has in the front

**Comment by Amrani-Farouk-Hossam-Eddine** [comment]
Hi, i want to work on the issue if there is no one currently working on it

**Comment by shaykres** [comment]
צריך להחליט מה עושים עם המשימה הזאת @Gil4390 @talgalm
