### ISSUE TITLE
BUG - done evaluating login again

### ISSUE THREAD

**Issue by Gil4390** [talgalm/Beautiful-Images-Project#66]
after finishing evaluating ~10 images and submitting them,
logging out using the logout button, and then login in again to start another experiment
resulted in duplicate images
![image](https://github.com/talgalm/Beautiful-Images-Project/assets/80397780/bf118a14-91e7-49c1-946f-b3396f4e1da0)

**Comment by shaykres** [comment]
can it be closed? @talgalm
