### ISSUE TITLE
באגים באדמין

### ISSUE THREAD

**Issue by shaykres** [talgalm/Beautiful-Images-Project#96]
באג בהוספת תמונה - אחרי שמוסיפים היא לא מופיעה בטבלה של התמונות
בעריכת קטגוריה לתמונה אנחנו אמורים לתמוך גם בAI PLUGIN אז צריך להוסיף את זה לשם
כשעורכים קטגוריה לתמונה זה לא מתעדכן בטבלה
כשנכנסים לעמודים של התמונות/הדירוגים הnav נעלם  - באג
כשמנסים ליצור דוחות csv הקובץ נראה ככה:
![image](https://github.com/talgalm/Beautiful-Images-Project/assets/71819815/a5209b66-dc9d-4dba-8c90-8fe970e7326e)
והpdf לא עובד
@Gil4390 אחרי שאתה מסדר את הדוחות תעדכן אותי כי צריך לתקף את מה שרשום ביוזקייס הזה

**Comment by Gil4390** [comment]
כשנכנסים לעמודים של התמונות/הדירוגים הnav נעלם - לא אומת
כשמנסים ליצור דוחות csv הקובץ נראה ככה - לא אומת
והpdf לא עובד - תוקן (אם בעתיד זה מוריד קבצים ריקים אז הולכים לקובץ Backend/src/Controllers/adminController.js לפונקציה generateAndFetchPdfReport ומגדילים את הTimeout)

**Comment by Gil4390** [comment]
באג בהוספת תמונה - אחרי שמוסיפים היא לא מופיעה בטבלה של התמונות
בעריכת קטגוריה לתמונה אנחנו אמורים לתמוך גם בAI PLUGIN אז צריך להוסיף את זה לשם
כשעורכים קטגוריה לתמונה זה לא מתעדכן בטבלה

זה ממש לא באג, זה פשוט לא מומש @talgMoveo
